import { MenuItem, Category, Table } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'breakfast-starters',
    nameGeo: 'საუზმე და სტარტერები',
    nameEng: 'Breakfast & Starters',
    iconName: 'Croissant',
  },
  {
    id: 'salads',
    nameGeo: 'სალათები',
    nameEng: 'Salads',
    iconName: 'Salad',
  },
  {
    id: 'sandwiches',
    nameGeo: 'სენდვიჩები',
    nameEng: 'Sandwiches',
    iconName: 'Sandwich',
  },
  {
    id: 'wine-bites',
    nameGeo: 'ღვინის დასაყოლებელი',
    nameEng: 'Wine Bites & Platters',
    iconName: 'Utensils',
  },
  {
    id: 'desserts',
    nameGeo: 'დესერტები',
    nameEng: 'Desserts',
    iconName: 'Cake',
  },
  {
    id: 'coffee',
    nameGeo: 'ყავა & სასმელები',
    nameEng: 'Coffee & Drinks',
    iconName: 'CupSoda',
  },
  {
    id: 'wine',
    nameGeo: 'ღვინის ასორტიმენტი',
    nameEng: 'Wine Collection',
    iconName: 'Wine',
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // BREAKFAST & STARTERS
  {
    id: 'truffle-omelette',
    nameGeo: 'საფირმო ტრიუფელის ომლეტი',
    nameEng: 'Signature Truffle Omelette',
    category: 'breakfast-starters',
    description: 'არომატული და მსუბუქი საუზმე. ნაზად ათქვეფილი კვერცხი შერწყმული მდიდრულ ტრიუფელის პასტასთან, ნაღებსა და პარმეზანთან. მიირთმევა ხრაშუნა ფრანგულ ბაგეტთან ერთად.',
    price: 24,
    isAvailable: true,
    tags: ['ვეგეტარიანული', 'საფირმო'],
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'burrata-berries',
    nameGeo: 'ბურატა თბილი კენკრით',
    nameEng: 'Burrata with Warm Berries',
    category: 'breakfast-starters',
    description: 'ხავერდოვანი ყველი ბურატა კრემოვანი შიგთავსით, რომელიც იდეალურ კონტრასტს ქმნის თბილი, კარამელიზებული კენკრის ნაღებთან. მოყრილი აქვს მოხალული ფსტა და ცოცხალი პიტნა.',
    price: 34,
    isAvailable: true,
    tags: ['ვეგეტარიანული'],
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'baked-camembert',
    nameGeo: 'გამომცხვარი კამამბერი',
    nameEng: 'Baked Camembert',
    category: 'breakfast-starters',
    description: 'ღუმელში ოქროსფრად გამომცხვარი, შიგნიდან მდნარი კამამბერი ნატურალური თაფლით, არომატული ნივრითა და ნედლი როზმარინით. მიირთმევა თბილ ხრაშუნა ბაგეტთან ერთად.',
    price: 36,
    isAvailable: true,
    tags: ['ვეგეტარიანული', 'ცხელი'],
    image: 'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'assorted-bruschetta',
    nameGeo: 'ბრუსკეტების ასორტი',
    nameEng: 'Assorted Bruschetta',
    category: 'breakfast-starters',
    description: 'სამი დახვეწილი ბრუსკეტა: ორაგულითა და კრემოვანი სტრაჩატელათი; სათუთი პროშუტო და ტკბილი ლეღვი; ნატურალური პესტო, არომატული ჩერი და მოცარელა.',
    price: 29,
    isAvailable: true,
    tags: ['ასორტი', 'პოპულარული'],
    image: 'https://images.unsplash.com/photo-1572656631137-7935297eff55?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // SALADS
  {
    id: 'stracciatella-salad',
    nameGeo: 'მწვანე სალათი სტრაჩატელათი',
    nameEng: 'Green Salad with Stracciatella',
    category: 'salads',
    description: 'ცოცხალი მწვანე ფოთლებისა და ხრაშუნა ნედლი კიტრის სალათი, შეზავებული იტალიური სტრაჩატელას ნაზი ფირფიტებით, არომატული პესტოთი და ლაიმის ნაზი სიმჟავით.',
    price: 28,
    isAvailable: true,
    tags: ['ვეგეტარიანული', 'ჯანსაღი'],
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'shrimp-salad',
    nameGeo: 'აზიური სალათი კრევეტებით',
    nameEng: 'Asian Shrimp Salad',
    category: 'salads',
    description: 'სათუთად შეზავებული ვეფხვისებრი კრევეტები, წარმოდგენილი ნორჩ სალათის ფოთლებთან, ჩერი პომიდორთან და პიკანტურ აზიურ დრესინგთან ერთად.',
    price: 38,
    isAvailable: true,
    tags: ['ზღვის პროდუქტები', 'პიკანტური'],
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // SANDWICHES
  {
    id: 'angus-sandwich',
    nameGeo: 'შავი ანგუსის სენდვიჩი',
    nameEng: 'Black Angus Beef Sandwich',
    category: 'sandwiches',
    description: 'ხრაშუნა ბაგეტში მოთავსებული ნაზი ანგუსის სუკის თხელი ფენები, მდნარი მოცარელა, რუკოლა და პიკანტური დიჟონის მდოგვის ნოტები.',
    price: 36,
    isAvailable: true,
    tags: ['პოპულარული'],
    image: 'https://images.unsplash.com/photo-1549611016-3a70d82b5040?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'prosciutto-sandwich',
    nameGeo: 'კლასიკური პროშუტო სენდვიჩი',
    nameEng: 'Classic Prosciutto Sandwich',
    category: 'sandwiches',
    description: 'ნედლად გამოყვანილი პრემიუმ პროშუტო, ნაზი მოცარელა, არომატული პესტო და ჩერი პომიდორი ხრაშუნა თბილ ბაგეტში.',
    price: 28,
    isAvailable: true,
    tags: ['იტალიური კლასიკა'],
    image: 'https://images.unsplash.com/photo-1522244459694-ade497d76fa6?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'salmon-sandwich',
    nameGeo: 'შებოლილი ორაგულის სენდვიჩი',
    nameEng: 'Smoked Salmon Sandwich',
    category: 'sandwiches',
    description: 'გახუხულ ბაგეტში განაწილებული შებოლილი ორაგულის ფირფიტები შერწყმული კრემ-ყველთან, ნედლ კიტრითან და ცოცხალ კამასთან.',
    price: 32,
    isAvailable: true,
    tags: ['ზღვის პროდუქტები', 'ჯანსაღი'],
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // WINE BITES & PLATTERS
  {
    id: 'beef-tartare',
    nameGeo: 'შავი ანგუსის ტარტარი',
    nameEng: 'Black Angus Beef Tartare',
    category: 'wine-bites',
    description: 'საუკეთესო ანგუსის სუკისგან სათუთად მომზადებული კლასიკური ტარტარი კაპერსებით, წითელი ხახვით, დიჟონის მდოგვითა და კვერცხის გულით. მიირთმევა თბილ ტოსტებთან ერთად.',
    price: 42,
    isAvailable: true,
    tags: ['გურმანი', 'ღვინისთვის'],
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'salmon-sashimi',
    nameGeo: 'ორაგულის საშიმი ლაიმით',
    nameEng: 'Salmon Sashimi with Lime',
    category: 'wine-bites',
    description: 'პრემიუმ კლასის შებოლილი ორაგულის სათუთი ნაჭრები, გაჯერებული ლაიმის ცოცხალი წვენით, ექსტრა ვირჯინ ზეითუნის ზეთითა და კაპერსებით.',
    price: 36,
    isAvailable: true,
    tags: ['ზღვის პროდუქტები', 'მინიმალისტური'],
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'baked-oysters',
    nameGeo: 'გამომცხვარი ხამანწკები პარმეზანით',
    nameEng: 'Baked Oysters with Parmesan (3 pcs)',
    category: 'wine-bites',
    description: 'სათუთად გამომცხვარი ხამანწკები მდნარი პარმეზანის ოქროსფერი ქერქით, ნივრიანი კარაქითა და არომატული მწვანილებით.',
    price: 45,
    isAvailable: true,
    tags: ['ზღვის პროდუქტები', 'ექსკლუზივი'],
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'seared-octopus',
    nameGeo: 'შემწვარი რვაფეხა',
    nameEng: 'Seared Octopus',
    category: 'wine-bites',
    description: 'სათუთად მოხრაკული რვაფეხას საცეცი, წარმოდგენილი უდიდესი ხავერდოვნების მქონე კარტოფილის მუსთან ერთად.',
    price: 58,
    isAvailable: true,
    tags: ['დელიკატესი', 'პოპულარული'],
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'cheese-platter',
    nameGeo: 'ევროპული ყველის დაფა',
    nameEng: 'European Cheese Platter',
    category: 'wine-bites',
    description: 'პრემიუმ ყველის ასორტი: ნაზი მოცარელა, პიკანტური ლურჯი ყველი, დავარგებული მდიდრული ქართული ყველი, ნატურალური თაფლი, ჩირეული და მოხალული თხილი.',
    price: 55,
    isAvailable: true,
    tags: ['ასორტი', 'ვეგეტარიანული'],
    image: 'https://images.unsplash.com/photo-1630132274431-b3b48416ca31?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'meat-platter',
    nameGeo: 'პრემიუმ ხორცის დაფა',
    nameEng: 'Premium Meat Platter',
    category: 'wine-bites',
    description: 'დახვეწილი ხორცის ასორტიმენტი: ჰაეროვანი პროშუტო, პიკანტური სალიამი, გიგანტური მწვანე ზეთისხილი და ხრაშუნა კორნიშონები.',
    price: 58,
    isAvailable: true,
    tags: ['ასორტი', 'ღვინისთვის'],
    image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // DESSERTS
  {
    id: 'cheesecake',
    nameGeo: 'ჩიზქეიქი',
    nameEng: 'Cheesecake',
    category: 'desserts',
    description: 'კლასიკური ნაზი ჩიზქეიქი ხავერდოვანი კრემოვანი ტექსტურითა და ხრაშუნა ორცხობილის ძირით. მიირთმევა ჩვენს საფირმო თბილი კენკრის სოუსთან ერთად.',
    price: 18,
    isAvailable: true,
    tags: ['ტკბილი', 'ბესტსელერი'],
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'tiramisu',
    nameGeo: 'ტირამუსი',
    nameEng: 'Tiramisu',
    category: 'desserts',
    description: 'საუცხოო იტალიური დესერტი. ყავაში გაჟღენთილი სავოიარდის ნამცხვარი, მსუბუქი მასკარპონეს კრემითა და არომატული კაკაოს ფხვნილით.',
    price: 16,
    isAvailable: true,
    tags: ['ტკბილი'],
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // COFFEE & DRINKS
  {
    id: 'espresso',
    nameGeo: 'ესპრესო',
    nameEng: 'Espresso',
    category: 'coffee',
    description: 'კლასიკური იტალიური ესპრესო ძლიერი ხასიათითა და სქელი ოქროსფერი კრემით.',
    price: 6,
    isAvailable: true,
    tags: ['ცხელი', 'კოფეინი'],
    image: 'https://images.unsplash.com/photo-1510707577719-ee7c2165749a?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'americano',
    nameGeo: 'ამერიკანო',
    nameEng: 'Americano',
    category: 'coffee',
    description: 'დახვეწილი და რბილი შავი ყავა - დიდი და პატარა პორცია თანაბარ ფასად.',
    price: 7,
    isAvailable: true,
    tags: ['ცხელი', 'კოფეინი'],
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'cappuccino-small',
    nameGeo: 'კაპუჩინო პატარა',
    nameEng: 'Cappuccino Small',
    category: 'coffee',
    description: 'ნაზი კაპუჩინო აბრეშუმისებრი რძის ქაფითა და ესპრესოს იდეალური ბალანსით.',
    price: 9,
    isAvailable: true,
    tags: ['ცხელი', 'რძით'],
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'cappuccino-large',
    nameGeo: 'კაპუჩინო დიდი',
    nameEng: 'Cappuccino Large',
    category: 'coffee',
    description: 'ორმაგი ესპრესო და მდიდარი, გულუხვი ჰაეროვანი რძის ქაფი შერჩეული პრემიუმ მარცვლებისგან.',
    price: 10,
    isAvailable: true,
    tags: ['ცხელი', 'რძით'],
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'flat-white',
    nameGeo: 'ფლეტ ვაითი',
    nameEng: 'Flat White',
    category: 'coffee',
    description: 'ინტენსიური, ორმაგი რიტრეტო რძის უთხელესი და ხავერდოვანი მიკროქაფით.',
    price: 10,
    isAvailable: true,
    tags: ['ცხელი', 'ძლიერი'],
    image: 'https://images.unsplash.com/photo-1577968897866-be573521c453?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'latte',
    nameGeo: 'ლატე',
    nameEng: 'Latte',
    category: 'coffee',
    description: 'კლასიკური ნაზი ლატე, მსუბუქი და ნაღებისებრი რძის გემოთი.',
    price: 12,
    isAvailable: true,
    tags: ['ცხელი', 'ნაზი'],
    image: 'https://images.unsplash.com/photo-1570968915860-54d5c301fc9f?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'iced-americano',
    nameGeo: 'ცივი ამერიკანო',
    nameEng: 'Iced Americano',
    category: 'coffee',
    description: 'გამაგრილებელი შავი ყავა ყინულებით - საუკეთესო ენერგია ზაფხულის ცხელ დღეებში.',
    price: 8,
    isAvailable: true,
    tags: ['ცივი', 'კოფეინი'],
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'iced-latte',
    nameGeo: 'ცივი ლატე',
    nameEng: 'Iced Latte',
    category: 'coffee',
    description: 'ორმაგი ესპრესო ცივი რძით, უხვი ყინულებითა და ნაზი, ჰაეროვანი რძის ქაფით.',
    price: 12,
    isAvailable: true,
    tags: ['ცივი', 'ნაზი'],
    image: 'https://images.unsplash.com/photo-1461023053936-af5ff4a49fc3?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'milk',
    nameGeo: 'რძე',
    nameEng: 'Milk',
    category: 'coffee',
    description: 'ნედლი, ნაღებისებური ან ალტერნატიული რძის პორცია თქვენი გემოვნებით.',
    price: 2,
    isAvailable: true,
    tags: ['დამატება'],
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // WHITE WINE (ქართული და იტალიური თეთრი ღვინოები)
  {
    id: 'chiche-tsinandali',
    nameGeo: 'Chiche • წინანდალი',
    nameEng: 'Chiche • Tsinandali',
    category: 'wine',
    description: 'კლასიკური თეთრი მშრალი ღვინო, წინანდლის მიკროზონიდან. ხასიათდება ციტრუსებისა და თეთრი ყვავილების დახვეწილი არომატებით.',
    price: 13,
    priceGlass: 13,
    priceBottle: 54,
    isAvailable: true,
    tags: ['თეთრი კლასიკური', '2024'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'damilie-kisi',
    nameGeo: 'Damilie • მადრასაული ქისი',
    nameEng: 'Damilie • Madrasauli Kisi',
    category: 'wine',
    description: 'მადრასაული ქისის გამორჩეული ტექსტურა, ხავერდოვანი ხასიათითა და მწიფე ყვითელი ხილის გამოხატული არომატით.',
    price: 18,
    priceGlass: 18,
    priceBottle: 78,
    isAvailable: true,
    tags: ['თეთრი კლასიკური', '2025'],
    image: 'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'first-winery-khikhvi',
    nameGeo: 'პირველი მეღვინეობა • ხიხვი კლასიკი',
    nameEng: 'First Winery • Khikhvi Classic',
    category: 'wine',
    description: 'იშვიათი ქართული ხიხვის ჯიშისგან დამზადებული კლასიკური თეთრი მშრალი ღვინო, ხილის ტონებითა და ნაზი მჟავიანობით.',
    price: 17,
    priceGlass: 17,
    priceBottle: 75,
    isAvailable: true,
    tags: ['თეთრი კლასიკური', 'კლასიკი'],
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'first-winery-kisi-classic',
    nameGeo: 'პირველი მეღვინეობა • ქისი კლასიკი',
    nameEng: 'First Winery • Kisi Classic',
    category: 'wine',
    description: 'ქისის საუკეთესო მოსავლიდან კლასიკური წესით დაყენებული უდახვეწილესი ღვინო, ატმისა და მინდვრის ყვავილების ნოტებით.',
    price: 21,
    priceGlass: 21,
    priceBottle: 90,
    isAvailable: true,
    tags: ['თეთრი კლასიკური', 'პრემიუმი'],
    image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'me-wine-chardonnay',
    nameGeo: 'Me&Wine • Chardonnay Sauvignon Blanc',
    nameEng: 'Me&Wine • Chardonnay Sauvignon Blanc',
    category: 'wine',
    description: 'შარდონესა და სოვინიონ ბლანის პრემიუმ კლასის კუპაჟი. ელეგანტური სხეული, მწიფე ტროპიკული ხილისა და მწვანე ვაშლის ინტენსიური გემოებით.',
    price: 21,
    priceGlass: 21,
    priceBottle: 90,
    isAvailable: true,
    tags: ['თეთრი კლასიკური', '2022'],
    image: 'https://images.unsplash.com/photo-1559261273-6fd47067c1ee?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'chiora-tsolikouri',
    nameGeo: 'Chiora • ლეჩხუმური ცოლიკოური',
    nameEng: 'Chiora • Lechkhumuri Tsolikouri',
    category: 'wine',
    description: 'უნიკალური ლეჩხუმური ტერუარიდან მიღებული გამორჩეული ცოლიკოური. ხასხასა, გამაგრილებელი მჟავიანობა და ციტრუსების ცოცხალი ნოტები.',
    price: 19,
    priceGlass: 19,
    priceBottle: 84,
    isAvailable: true,
    tags: ['თეთრი კლასიკური', '2023'],
    image: 'https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // QVEVRI & AMBER (ქვევრი & ქარვისფერი)
  {
    id: 'damilie-goruli-mtsvane',
    nameGeo: 'Damilie • გორული მწვანე-ჩინური',
    nameEng: 'Damilie • Goruli Mtsvane - Chinuri',
    category: 'wine',
    description: 'ქვევრში ტრადიციული წესით დაყენებული ქარვისფერი ღვინო. გამოირჩევა ხმელი ხილის, თხილისა და სანელებლების სასიამოვნო სურნელით.',
    price: 17,
    priceGlass: 17,
    priceBottle: 75,
    isAvailable: true,
    tags: ['ქვევრი & ქარვისფერი', '2023'],
    image: 'https://images.unsplash.com/photo-1613564834361-9436948817d1?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'first-winery-kisi-qvevri',
    nameGeo: 'პირველი მეღვინეობა • ქისი ქვევრი',
    nameEng: 'First Winery • Kisi Qvevri',
    category: 'wine',
    description: 'ქვევრის უბადლო ქარვისფერი ღვინო ქისის ჯიშისგან. ხავერდოვანი ტანინები, გამომშრალი გარგარისა და თაფლის ღრმა ნოტებით.',
    price: 19,
    priceGlass: 19,
    priceBottle: 84,
    isAvailable: true,
    tags: ['ქვევრი & ქარვისფერი', 'ტრადიციული'],
    image: 'https://images.unsplash.com/photo-1594498541225-52ac5c2104bd?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'first-winery-khikhvi-qvevri',
    nameGeo: 'პირველი მეღვინეობა • ხიხვი ქვევრი',
    nameEng: 'First Winery • Khikhvi Qvevri',
    category: 'wine',
    description: 'ხიხვის ძვირფასი ქვევრის სტილი. მდიდარი ტექსტურა, შესანიშნავად შერწყმული მდგრად ტანინებთან და ჩირეულის ხასიათთან.',
    price: 19,
    priceGlass: 19,
    priceBottle: 84,
    isAvailable: true,
    tags: ['ქვევრი & ქარვისფერი', 'მდიდარი'],
    image: 'https://images.unsplash.com/photo-1543418219-44e2bf8516ee?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'tevza-chinuri',
    nameGeo: 'Tevza • ჩინური',
    nameEng: 'Tevza • Chinuri',
    category: 'wine',
    description: 'უნაზესი და სათუთი ქვევრის ჩინური. მსუბუქი სხეული, მინდვრის მწვანილებისა და ნედლი ნუშის ტონებით.',
    price: 18,
    priceGlass: 18,
    priceBottle: 78,
    isAvailable: true,
    tags: ['ქვევრი & ქარვისფერი', '2022'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'chiche-4-grafini',
    nameGeo: 'Chiche • 4 გრაფინი',
    nameEng: 'Chiche • 4 Grafini',
    category: 'wine',
    description: 'უნიკალური ბლენდი: ქისი, ხიხვი და მწვანე ერთად. მდიდარი, მრავალფეროვანი და საინტერესო ქარვისფერი სტრუქტურა.',
    price: 16,
    priceGlass: 16,
    priceBottle: 69,
    isAvailable: true,
    tags: ['ქვევრი & ქარვისფერი', 'ნაკრები'],
    image: 'https://images.unsplash.com/photo-1562601519-1b4de05365d5?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // RED WINE (წითელი ღვინოები)
  {
    id: 'chiche-saperavi',
    nameGeo: 'Chiche • საფერავი',
    nameEng: 'Chiche • Saperavi',
    category: 'wine',
    description: 'ინტენსიური, სხეულიანი წითელი მშრალი ღვინო, მწიფე მაყვლისა და მუქი ბლის ძლიერი ტონებით.',
    price: 17,
    priceGlass: 17,
    priceBottle: 75,
    isAvailable: true,
    tags: ['წითელი ღვინოები', '2022'],
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'first-winery-saperavi-classic',
    nameGeo: 'პირველი მეღვინეობა • საფერავი კლასიკი',
    nameEng: 'First Winery • Saperavi Classic',
    category: 'wine',
    description: 'დახვეწილი კლასიკური საფერავი, მუხის მსუბუქი ნოტებითა და წითელი კენკრის ცოცხალი ხასიათით.',
    price: 15,
    priceGlass: 15,
    priceBottle: 66,
    isAvailable: true,
    tags: ['წითელი ღვინოები', 'პოპულარული'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'first-winery-saperavi-qvevri',
    nameGeo: 'პირველი მეღვინეობა • საფერავი ქვევრი',
    nameEng: 'First Winery • Saperavi Qvevri',
    category: 'wine',
    description: 'ქვევრში დავარგებული მდიდარი საფერავი. გამოირჩევა სქელი, ხავერდოვანი ტანინებითა და შავი ქლიავის ჩირის არომატით.',
    price: 21,
    priceGlass: 21,
    priceBottle: 90,
    isAvailable: true,
    tags: ['წითელი ღვინოები', 'ქვევრი'],
    image: 'https://images.unsplash.com/photo-1528826722302-d6084efcd8e5?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'damilie-dzelshavi',
    nameGeo: 'Damilie • ძელშავი',
    nameEng: 'Damilie • Dzelshavi',
    category: 'wine',
    description: 'იშვიათი იმერული ძელშავის ჯიშისგან მიღებული მსუბუქი, ელეგანტური და ხალისიანი წითელი ღვინო კენკროვანი ნოტებით.',
    price: 20,
    priceGlass: 20,
    priceBottle: 87,
    isAvailable: true,
    tags: ['წითელი ღვინოები', '2024'],
    image: 'https://images.unsplash.com/photo-1553187184-d227914619ee?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'critera-primitivo',
    nameGeo: 'Critera Primitivo (იტალია)',
    nameEng: 'Critera Primitivo (Italy)',
    category: 'wine',
    description: 'მდიდარი და რბილი იტალიური პრიმიტივო სამხრეთ იტალიის თბილი მზიდან. შოკოლადისა და მწიფე ალუბლის ჰარმონია.',
    price: 18,
    priceGlass: 18,
    priceBottle: 78,
    isAvailable: true,
    tags: ['წითელი ღვინოები', 'იტალიური'],
    image: 'https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'corte-badin',
    nameGeo: 'Corte Badin 1931 (იტალია)',
    nameEng: 'Corte Badin 1931 (Italy)',
    category: 'wine',
    description: 'ავთენტური იტალიური რეცეპტურით დაყენებული წითელი მშრალი ღვინო, ხავერდოვანი ტანინებითა და ხანგრძლივი გემოთი.',
    price: 16,
    priceGlass: 16,
    priceBottle: 72,
    isAvailable: true,
    tags: ['წითელი ღვინოები', 'გურმანი'],
    image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'camponi-rosso',
    nameGeo: 'I Camponi Rosso Veronese',
    nameEng: 'I Camponi Rosso Veronese',
    category: 'wine',
    description: 'ცნობილი ვერონული სტილის უმაღლესი ხარისხის წითელი კუპაჟი. რბილი, სანელებლებისა და გამხმარი ხილის ტონებით.',
    price: 16,
    priceGlass: 16,
    priceBottle: 72,
    isAvailable: true,
    tags: ['წითელი ღვინოები', '2019'],
    image: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // SPARKLING & PET-NAT (ცქრიალა & პეტნატი)
  {
    id: 'prosecco-fili',
    nameGeo: 'Prosecco Fili Extra Dry (იტალია)',
    nameEng: 'Prosecco Fili Extra Dry (Italy)',
    category: 'wine',
    description: 'ხალისიანი და გამაგრილებელი იტალიური პროსეკო თხელი, დახვეწილი ბუშტუკებითა და ხილის ნაზი სიტკბოთი.',
    price: 21,
    priceGlass: 21,
    priceBottle: 90,
    isAvailable: true,
    tags: ['ცქრიალა & პეტნატი', 'ექსტრა მშრალი'],
    image: 'https://images.unsplash.com/photo-1594498653385-d5172b532c00?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'mille-bolle-rose',
    nameGeo: 'Mille Bolle Spumante Rosé Brut',
    nameEng: 'Mille Bolle Spumante Rosé Brut',
    category: 'wine',
    description: 'ცქრიალა ვარდისფერი ბრუტი იტალიიდან. ცოცხალი კენკროვანი ხასიათი და ელეგანტური ბუშტუკების თამაში.',
    price: 16,
    priceGlass: 16,
    priceBottle: 69,
    isAvailable: true,
    tags: ['ცქრიალა & პეტნატი', 'როზე ბრუტი'],
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'damilie-petnat-tsolikouri',
    nameGeo: 'Damilie Pet-Nat • ცოლიკოური',
    nameEng: 'Damilie Pet-Nat • Tsolikouri',
    category: 'wine',
    description: 'ნატურალური ცქრიალა ყურძნის სასმელი (პეტნატი) ცოლიკოურის ჯიშისგან. ცოცხალი, დაფილტრავი გემოების აუთენტური გამოცდილება.',
    price: 19,
    priceGlass: 19,
    priceBottle: 81,
    isAvailable: true,
    tags: ['ცქრიალა & პეტნატი', '2024'],
    image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=500&h=500&q=80',
  },

  // ROSÉ (როზე)
  {
    id: 'chiche-rose',
    nameGeo: 'Chiche • შარდონე საფერავი',
    nameEng: 'Chiche • Chardonnay Saperavi Rosé',
    category: 'wine',
    description: 'ვარდისფერი მშრალი მარგალიტი. შარდონეს სინაზე და საფერავის ხავერდოვნება ქმნის ზაფხულის საუკეთესო როზეს.',
    price: 13,
    priceGlass: 13,
    priceBottle: 54,
    isAvailable: true,
    tags: ['როზე', '2024'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=500&h=500&q=80',
  },
  {
    id: 'antieri-rose',
    nameGeo: 'Antieri Rosé (იტალია)',
    nameEng: 'Antieri Rosé (Italy)',
    category: 'wine',
    description: 'უმაღლესი კლასის იტალიური როზე, მინდვრის მარწყვისა და წითელი მოცხარის კეთილშობილური ნოტებით.',
    price: 25,
    priceGlass: 25,
    priceBottle: 108,
    isAvailable: true,
    tags: ['როზე', 'პრემიუმი'],
    image: 'https://images.unsplash.com/photo-1504198266287-1659872e6590?auto=format&fit=crop&w=500&h=500&q=80',
  },
];

export const INITIAL_TABLES: Table[] = [
  { id: '1', number: 1, name: 'მაგიდა #1 (ტერასა)', status: 'free', activeGreeting: 'კეთილი იყოს თქვენი მობრძანება ხალისიან ტერასაზე!' },
  { id: '2', number: 2, name: 'მაგიდა #2 (შუშის დარბაზი)', status: 'free', activeGreeting: 'გისურვებთ სასიამოვნო დროს ჩვენს მყუდრო შუშის სივრცეში.' },
  { id: '3', number: 3, name: 'მაგიდა #3 (VIP ყუთი)', status: 'free', activeGreeting: 'მოხარულნი ვართ გიმასპინძლოთ კერძო VIP დარბაზში.' },
  { id: '4', number: 4, name: 'მაგიდა #4 (ბარი)', status: 'free', activeGreeting: 'სასიამოვნო საღამოს გისურვებთ აქტიურ ბართან!' },
  { id: '5', number: 5, name: 'მაგიდა #5 (ბაღი)', status: 'free', activeGreeting: 'განიტვირთეთ ჩვენს წყნარ და მწვანე შიდა ეზოში.' },
];
